version: '3.1'
services:
  web: &app_base
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - UID=${UID-1000}
        - APP_HOME=${PWD}
    ports:
     - "3333:3333"
    command: rails s -b 0.0.0.0
    stdin_open: true
    tty: true
    links:
     - db
     - vault
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    environment: &env_base
      PORT: 3333
      DATABASE_URL: postgres://postgres:@db:5432
      ENCRYPTION_KEY: abcdefghijklmn
      GITHUB_ORGANIZATION: 'degica'
      GITHUB_DEVELOPER_TEAM: 'developers'
      GITHUB_ADMIN_TEAM: 'Admin developers'
      VAULT_URL: http://vault:8200
      VAULT_PATH_PREFIX: degica
  worker:
    <<: *app_base
    ports: []
    command: rake jobs:work
  spring:
    <<: *app_base
    ports: []
    command: spring server
    pid: host
    volumes:
      - bundle:/usr/local/bundle
      - .:${PWD}
  db:
    image: postgres:9.5
    environment:
      PGDATA: /data
    healthcheck:
      test: echo "\\l" | psql -U postgres
    volumes:
      - pgdata:/data
  vault:
    image: vault:0.7.2
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: "true"
      VAULT_DEV_ROOT_TOKEN_ID: root-token
volumes:
  pgdata:
  bundle:
